# Generated by Django 5.0.2 on 2024-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={},
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(default="saeed", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(default="mahmoudi", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(),
        ),
    ]
